name = "numberbarn2telegram"
main = "index.js"
compatibility_date = "2023-10-13"

kv_namespaces = [
  { binding = "DATABASE", id = "your_database_id" }
]

[vars]

TELEGRAM_ID = ""
TELEGRAM_TOKEN = ":"